#!/usr/bin/env python3
"""P5 — turn scored ablation cells into a LaTeX table and a decision skeleton.

Consumes `ablation-scores.json` (written by `score_ablation_cells.py`) and emits:

  * a booktabs table in the same style as the Sprint-14 voicing table, with
    paired deltas against control and significance marks;
  * a decision memo skeleton listing, per axis, what the evidence supports —
    with the numbers filled in, and the judgement left to the author.

The memo deliberately does NOT auto-conclude. Choosing a configuration for a
65-hour run is a judgement about which trade-offs are acceptable, and a script
that asserted "adopt variant X" from a handful of paired seeds would be
laundering a five-seed result into a recommendation.

Usage:
    python llm/report_ablation.py
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
SPRINT = BASE_DIR / "agora/analysis/sprint-15-ablation-prep"
DEFAULT_SCORES = SPRINT / "ablation-scores.json"
DEFAULT_TEX = BASE_DIR / "pipeline/output/reports/ablation/ablation_deltas.tex"
DEFAULT_MEMO = SPRINT / "sprint-15-decision-memo.md"

# Outcome -> which axis it primarily informs, for the memo grouping.
AXIS_OF = {
    "distinct args / agent": "prompt",
    "top-cid share": "prompt",
    "distinct args / room": "prompt",
    "saturation @r1": "mechanism",
    "DRI (final)": "headline",
    "meta-consensus (final)": "headline",
    "opinion var (final)": "headline",
    "LLM calls / run": "cost",
}


def stars(p: float | None) -> str:
    if p is None:
        return ""
    return "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else ""


def build_tex(rows: list[dict], out: Path) -> None:
    by_cell: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_cell[r["cell"]].append(r)
    lines = [
        "% Auto-generated by llm/report_ablation.py — do not edit.",
        r"\begin{table}[htbp]", r"\centering", r"\small",
        r"\caption{Sprint-15 ablation cells against the production control, "
        r"paired by seed. Each cell runs the identical (composition, seed) grid, "
        r"so entries are mean paired differences and the test is a paired "
        r"$t$-test. Significance: $^{*}p<.05$, $^{**}p<.01$, $^{***}p<.001$.}",
        r"\label{tab:ablation-deltas}",
        r"\begin{tabular}{llrrrr}", r"\toprule",
        r"Cell & Outcome & Control & Variant & $\Delta$ & $p$ \\", r"\midrule",
    ]
    for i, (cell, entries) in enumerate(sorted(by_cell.items())):
        if i:
            lines.append(r"\midrule")
        first = True
        for e in entries:
            name = cell.replace("_", r"\_") if first else ""
            first = False
            p = "" if e["p"] is None else ("$<$.001" if e["p"] < 0.001 else f"{e['p']:.3f}")
            lines.append(
                f"{name} & {e['outcome']} & {e['control']:.3f} & {e['variant']:.3f} & "
                f"{e['delta']:+.3f}{stars(e['p'])} & {p} \\\\"
            )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))


def build_memo(rows: list[dict], out: Path) -> None:
    by_cell: dict[str, dict[str, dict]] = defaultdict(dict)
    for r in rows:
        by_cell[r["cell"]][r["outcome"]] = r

    def fmt(cell: str, outcome: str) -> str:
        e = by_cell.get(cell, {}).get(outcome)
        if not e:
            return "not collected"
        p = "n/a" if e["p"] is None else ("<.001" if e["p"] < 0.001 else f"{e['p']:.3f}")
        return f"{e['control']:.3f} → {e['variant']:.3f} ({e['delta']:+.3f}, p={p})"

    md = [
        "# Sprint 15 — Ablation Decision Memo",
        "",
        "**Status:** DRAFT — numbers auto-filled, judgement left to the author.",
        "",
        "Purpose: decide the configuration for extending Arm B from 390 to 1200",
        "runs (~65 GPU hours), on evidence rather than default.",
        "",
        "## Cells collected",
        "",
        "| Cell | Runs paired |",
        "|---|---|",
    ]
    for cell in sorted(by_cell):
        n = max((e["n_pairs"] for e in by_cell[cell].values()), default=0)
        md.append(f"| `{cell}` | {n} |")
    md += ["", "## Axis 1 — prompt", ""]
    for cell in sorted(c for c in by_cell if c.startswith("prompt_")):
        md += [
            f"### `{cell}`", "",
            f"- distinct args / agent: {fmt(cell, 'distinct args / agent')}",
            f"- top-cid share: {fmt(cell, 'top-cid share')}",
            f"- saturation @r1 (mechanism): {fmt(cell, 'saturation @r1')}",
            f"- DRI final (headline): {fmt(cell, 'DRI (final)')}",
            f"- meta-consensus final (headline): {fmt(cell, 'meta-consensus (final)')}",
            "",
            "Reading: if voicing diversity moves while saturation does not, the",
            "repetition documented in Sprint 14 was prompt-induced; if neither",
            "moves, it is a property of the engine's state dynamics.",
            "",
        ]
    md += ["## Axis 2a — reasoning", ""]
    for cell in sorted(c for c in by_cell if c.startswith("reasoning_")):
        md += [
            f"### `{cell}`", "",
            f"- saturation @r1: {fmt(cell, 'saturation @r1')}",
            f"- distinct args / agent: {fmt(cell, 'distinct args / agent')}",
            f"- DRI final: {fmt(cell, 'DRI (final)')}",
            f"- LLM calls / run (cost proxy): {fmt(cell, 'LLM calls / run')}",
            "",
        ]
    md += ["## Axis 2b — quantization", ""]
    for cell in sorted(c for c in by_cell if c.startswith("quant_")):
        md += [
            f"### `{cell}`", "",
            f"- DRI final: {fmt(cell, 'DRI (final)')}",
            f"- meta-consensus final: {fmt(cell, 'meta-consensus (final)')}",
            f"- distinct args / agent: {fmt(cell, 'distinct args / agent')}",
            "",
            "Watch tool-call reliability here specifically: the parse-500 class is",
            "a formatting failure and is the most likely casualty of heavier",
            "quantization (see Sprint 14 §"
            "on the llama-server parse-500 replay behaviour).",
            "",
        ]
    md += [
        "## Decision (author)",
        "",
        "- [ ] Prompt configuration for the 1200-run extension: ______",
        "- [ ] Reasoning on/off (and budget if on): ______",
        "- [ ] Quantization: ______",
        "",
        "### Caveats to carry",
        "",
        "- Five seeds per composition is enough to detect large paired effects and",
        "  nothing else. A null here is 'not detected at this power', not 'absent'.",
        "- Cells were collected in one session on one machine; any driver or",
        "  serving change between a cell and the main run invalidates the pairing.",
        "- Table 10 provenance (Sprint 14) is unresolved for Arm A; nothing in this",
        "  memo bears on that.",
        "",
    ]
    out.write_text("\n".join(md))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--scores", type=Path, default=DEFAULT_SCORES)
    ap.add_argument("--tex", type=Path, default=DEFAULT_TEX)
    ap.add_argument("--memo", type=Path, default=DEFAULT_MEMO)
    args = ap.parse_args()

    if not args.scores.exists():
        print(f"[abort] {args.scores} not found — run score_ablation_cells.py first")
        return 2
    rows = json.loads(args.scores.read_text())
    if not rows:
        print("[abort] no scored rows; no cells collected yet")
        return 2
    build_tex(rows, args.tex)
    build_memo(rows, args.memo)
    print(f"wrote {args.tex}\nwrote {args.memo}")
    print(f"cells: {sorted({r['cell'] for r in rows})}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
